name: Build Test Deploy

on:
  push:
    branches:
      - main

env: 
  PROJET_VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - uses: actions/checkout@v6.0.0
      - name: Récupération du JDK 25
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 25
          distribution: microsoft
      - name: Construction du package jar
        run: mvn clean package -DskipTests

  tests:
    name: Exécuter les tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Lancement des tests"
        run: "mvn test"
      
